// <auto-generated />
namespace LoginApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class todt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(todt));
        
        string IMigrationMetadata.Id
        {
            get { return "202504240842180_todt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
